### PR TITLE
MAINT: Sync with upstream changes

### PR DESCRIPTION
**Pull request by bashtage**
Pull in BasicRNG source changes from original author
Small doc fixes

### CODE REVIEW

**Comment by bashtage** [comment]
Should be the last one.

**Comment by mattip** [comment]
@bashtage There are many documentation build warnings in bashtage/randomgen about the footnotes. Apparently they are never actually referenced.

**Comment by bashtage** [comment]
I think the references are in the same format as in the mtrand module in
released Numpy. Are these problems?

**Comment by mattip** [comment]
See these [warnings](https://travis-ci.org/bashtage/randomgen/jobs/514664628#L2784) in bashtage/randomgen builds

**Comment by bashtage** [comment]
Yes, I just ignore those.  I assume that NumPy's doc system is happy to ignore these too (or doesn't create them in the first place), since there are many examples that are identical,

[https://github.com/numpy/numpy/blob/master/numpy/random/mtrand/mtrand.pyx#L1797](https://github.com/numpy/numpy/blob/master/numpy/random/mtrand/mtrand.pyx#L1797)

**Comment by bashtage** [comment]
It is possible numpydoc fixes these.  I use napoleon in randomgen.

**Comment by mattip** [comment]
Switching to numpydoc (in bashtage/randomgen) is worse: it now emits many warnings of the form
```
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 198 source files that are out of date
updating environment: 198 added, 0 changed, 0 removed
reading sources... [100%] references                                                                                                          
docstring of randomgen.dsfmt.DSFMT:105: WARNING: toctree references unknown document 'brng/randomgen.dsfmt.DSFMT.jump'
docstring of randomgen.dsfmt.DSFMT:105: WARNING: toctree references unknown document 'brng/randomgen.dsfmt.DSFMT.random_raw'
docstring of randomgen.dsfmt.DSFMT:105: WARNING: toctree references unknown document 'brng/randomgen.dsfmt.DSFMT.seed'
...
```

This is the diff (requires pip install numpydoc)
```
diff --git a/doc/source/conf.py b/doc/source/conf.py
index d4290d17..6fd7bcb5 100644
--- a/doc/source/conf.py
+++ b/doc/source/conf.py
@@ -43,8 +43,9 @@ release = randomgen.__version__
 # extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
 # ones.
 extensions = [
-    'sphinx.ext.napoleon',
+    #'sphinx.ext.napoleon',
     'sphinx.ext.autodoc',
+    'numpydoc',
     'sphinx.ext.extlinks',
     'sphinx.ext.todo',
     'sphinx.ext.doctest',

```

**Comment by mattip** [comment]
numpy/numpydoc#204

**Comment by bashtage** [comment]
Seems to generate a ton of warnings but also works.

**Comment by mattip** [comment]
I built both and diffed the html. Indeed the differences are only the docstring results.
Must be more of numpy/numpydoc#184. Now I need to find out why the `:orphan:` work around in `doc/source/_templates/autosummary/*.rst` in numpy is not preventing the warning.

**Pull request merged**
