### PR TITLE
ENH: Speedup ufunc.at for a fast-path of numeric dtypes

### PR DESCRIPTION
**Pull request by mattip**
Towards fixing numpy/numpy#5922. The idea is to make a fast-path that will avoid creating a casting-iterator, and maybe other speedups to have a single iterator instead of two. One constraint: the `PyArrayMapIterObject` is not a `PyMultiIterator`: it only holds one ndarray.

### CODE REVIEW

**Comment by mattip** [comment]
Found another two optimizations, now the speedup is about 9x better:

      before           after         ratio
     [cd007c4f]       [6518cfe0]
     <speedup-ufunc.at~8>       <speedup-ufunc.at>
-     72.9±0.04ms      8.37±0.01ms     0.11  bench_ufunc.At.time_sum_at

    the function call was going through a wrapper. Moving the "unwrap" out of the hot loop got me to 4x
    the inner loop functions have some overhead since for every call they go through a "can I use a SIMD optimization of 128 bit vectors? No, so maybe 64 bit vectors? No, so maybe ...". This works well when dealing with a contiguous chunk of memory once. For the ufunc_at case, the inner loop function is called with a single data point, so all that is wasted effort. Short-circuiting the checks if count<4 gets an over 2x speed increase.

**Comment by mattip** [comment]
close/open to retrigger CI

**Comment by seiko2plus** [comment]
> the function call was going through a wrapper. Moving the "unwrap" out of the hot loop got me to 4x
the inner loop functions have some overhead since for every call they go through a "can I use a SIMD optimization of 128 bit vectors? No, so maybe 64 bit vectors? No, so maybe ...".

If you mean runtime dispatching based on the highest interest of enabled CPU features, then no it happens only one time during initiating umath module.

But is there overhead that may affect on the small array? oh yes but almost nothing and only for basic operations that have native instructions, such `<<>>>==<|!&+-/*` etc, this overhead is due to nested branching, for example:
- checking memory overlap
- checking the strides(contig, non-contig, reduce, scalar, etc..)

**Comment by mattip** [comment]
> But is there overhead that may affect on the small array? oh yes but almost nothing 

well, removing that overhead gave a 2x speed increase in this PR (see [the analysis](https://github.com/numpy/numpy/pull/22889#issuecomment-1366487947) for commit cfa2b17695 in the PR to numpy/numpy #22889

**Pull request closed without merging**
